import React from "react";
import Header from "../components/Header";
import Head from "next/head";

function Email() {
  return (
    <div>
      <Head>
        <title>Ben Grieve-Fitzell | Email</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex justify-center mt-28 text-xl font-semibold">
          <h1>bgf@grievefitzell.com</h1>
        </div>
      </main>
    </div>
  );
}

export default Email;
