import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import EssayFeed from "../components/EssayFeed";

function Essays() {
  return (
    <>
      <Head>
        <title>Ben Grieve-Fitzell | Essays</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <EssayFeed />
      </main>
    </>
  );
}

export default Essays;
