import React from "react";
import Head from "next/head";

function PatentEssay() {
  return (
    <>
      <Head>
        <title>Ben Grieve-Fitzell | Should I file for a patent?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8">
        <h1 className="text-lg font-semibold pb-5">
          Should I file for a patent?
        </h1>{" "}
        While coming up with business ideas in the past, like many others, I
        have thought about filing for patents to ensure the idea won’t be
        stolen. The only problem was, they can be extremely expensive for the
        average working class person. While dwelling on the idea of patents and
        intellectual property in the tech startup space, I came to the
        conclusion that it might not be the best thing. Let me explain… As a
        tech start up, VC’s require you, most of the time, if not all of the
        time, to have a patent for your invention or idea. This is obviously to
        ensure investors profit and get their money’s worth. But this comes at a
        cost… If a founder is after money, it is probably best to file for
        patents to ensure you crush any potential competition and to guarantee
        you have enough capital at your disposal from VC’s to beat your burn
        rate. The problem with this is the macro impact it has on society. When
        a founder and that founder’s investors chase money, they can inherit
        tunnel vision, and the only goal at the end of that long, thin tunnel,
        is money, the big picture isn’t taken into account. What is the big
        picture? Customer satisfaction and the company’s initial vision of
        solving a problem. When founders focus on profit, they most likely won’t
        get what they want, profit is only a by-product of extreme customer
        satisfaction. It isn’t investors that dictate the success of a startup
        as much as many people want to believe that… it’s the customers. Product
        development should always be at the centre of every company. I’m a
        combination of a rationalist and an empiricist, however I lean more on
        the empiricist side. As an empiricist, I have observed that all of the
        most successful tech companies (I can’t mention other industries as I
        haven’t done enough research, however the outcomes are more likely than
        not the same) have one thing in common: customer centricity. Amazon’s
        company is built on a solid foundation of customer centricity. It is
        clear that their main product, being the Amazon eCommerce platform, is
        an EXTREME example of customer satisfaction. Imagine the look on
        someone’s face in the 70’s if you were to somehow travel back in time
        and tell them that in the 2000’s, they’ll be able to buy ANYTHING they
        want in the comfort of their home, and that item would be delivered the
        next day or sometimes on the same day… The question is, what is the best
        way to drive innovation in product development? I believe that anyone
        can be consistently content, even if they have bad days. Happiness and
        sadness are only impulsive, emotional, temporary responses to a present
        situation, to feel content… thats permanent. If you have done something
        so great, and which has made an enormous positive impact on an insane
        amount of people, you will be content. I have designed a formula that
        proves this: Level of content = Amount of people helped * Amount of help
        given to each person. (Level of content/Amount of people helped, will
        give you the amount you’ve helped each person). The formula works in
        every arrangement. You might be thinking to yourself: “What in the world
        does this rambling have to do with patents?!” My hypothesis is that
        patents stunt innovation. When a project is open source, everyone
        interested in that topic will form a sort of collective consciousness to
        tackle that project, not for money, but for humanity. The more minds
        there are tackling a certain problem, the faster the solution will be
        designed and created… Think of it in a deep learning sense: Each brain
        represents a node in the neural network, brains that think in the
        same/similar way (e.g system thinking or abstract thinking) are grouped
        together to form each layer of the neural net. When the problem (the
        input) is inputed into the network, the first layer (system thinking
        brains) perform their specific function, then the second layer (abstract
        brains). The data is then back propagated and repeated through the
        network to generate an output (the solution). In terms of statistics,
        assuming the standard deviation is large in terms of different types of
        brains in the whole sample space (High variation in types), The neural
        network will perform better because more variation means more layers
        which means the network gets deeper. This is exactly what is happening
        in the Deep Learning world. Shallow, wide nets, are very good at
        memorisation but not so good at generalisation. There is even evidence
        of this in the business world: Companies are started by generalists, who
        initially build, but hire specialists to scale. Another example is that
        traditional school is for memorisation and, at university level,
        specialisation. Ironically, the intellectuals of our world have a very
        broad knowledge base and have brains that compute not just “wider” in
        terms of neural nets, but “deeper” (High variation). So what am I
        proposing? A single company can only have a limited amount of variation,
        meaning a less efficient collective consciousness/neural net. If that
        company goes ahead and patents an idea, that idea can’t then be worked
        on by external intellectuals, which according to my observation, means
        that the problem solving ability of that single company, will be
        inferior to the problem solving ability of an open source community. The
        open source community’s network, by nature, will not just be wider, but
        also deeper. Even if the external parties involved in solving the
        problem were other companies, this would still be a better solution if
        the goal is innovation. Darwin observed this when he proposed the idea
        of evolution through natural selection. If the idea was open source to
        all companies, the company with the best collective consciousness of
        employees would create and evolve the most efficient solution possible.
        After all, if you have a collection of identical neural networks, but
        give each a different amount of data to learn from, the network with the
        most data will be more accurate. Naturally, companies that couldn’t meet
        that level of innovation, would perish. In conclusion, if the goal of
        your company is to genuinely make a positive impact on society, make as
        much data as possible open source.
      </main>
    </>
  );
}

export default PatentEssay;
